# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BoredApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BoredApp

  target 'BoredAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BoredAppUITests' do
    # Pods for testing
  end

end
