name: Swift

on: [push]
  # push:
  #   branches: 
  #   - develop
  #   - setup-github-action
  # pull_request:
  #   branches: 
  #   - develop
  #   - setup-github-action

jobs:
  test:

    runs-on: macos-latest
    timeout-minutes: 15

    steps:
    
    - name: Cancel previous jobs
      uses: styfle/cancel-workflow-action@0.6.0
      with:
        access_token: ${{ github.token }}

    - name: Git - Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
    - name: Setup - Xcode
      run: sudo xcode-select -s /Applications/Xcode_13.4.1.app
    - name: Setup - Ruby and bundler dependencies
      uses: ruby/setup-ruby@v1.57.0
      with:
        ruby-version: 2.4.0
        bundler-cache: true
    - name: Test - Fastlane tests
      run: bundle exec fastlane test
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v